version: "3.8"
services:
    frontend:
        build:
            context: ./FE
            dockerfile: Dockerfile
        container_name: frontend
        working_dir: /var/www/html/TESTNE_MASTER/FE
        ports:
            - "3000:3000"  # Vite sẽ chạy trên cổng 3000
        volumes:
            - ./FE:/var/www/html/TESTNE_MASTER/FE
            - /var/www/html/TESTNE_MASTER/FE/node_modules
        networks:
            - quanlyphongtro
        depends_on:
            - backend  # Đảm bảo frontend khởi động sau backend

    backend:
        build:
            context: ./BE
            dockerfile: Dockerfile
        container_name: backend
        working_dir: /var/www/html/TESTNE_MASTER/BE
        volumes:
            - ./BE:/var/www/html/TESTNE_MASTER/BE
            - /var/www/html/TESTNE_MASTER/BE/node_modules
        ports:
            - "5000:5000"
        networks:
            - quanlyphongtro
        environment:
            - NODE_ENV=development
            - DB_HOST=mongodb://mongo:27017  # Kết nối tới MongoDB container qua tên dịch vụ
            - DB_NAME=quanlyphongtro  # Tên database MongoDB
            - DB_USERNAME=admin # Tên người dùng MongoDB
            - DB_PASSWORD=123456  # Mật khẩu MongoDB
            - DB_PORT=27017  # Cổng MongoDB
            - DB_USER=User
        depends_on:
            - mongo  # Đảm bảo backend khởi động sau MongoDB

    webserver:
        image: nginx:alpine
        container_name: nginx_qlpt
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./FE:/var/www/html/TESTNE_MASTER/FE
        networks:
            - quanlyphongtro
        depends_on:
            - frontend  # Đảm bảo webserver khởi động sau frontend

    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/var/lib/mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=123456
            - MONGO_INITDB_DATABASE=quanlyphongtro
        networks:
            - quanlyphongtro

networks:
    quanlyphongtro:

volumes:
    mongo_data:
